services:
  valheim:
    image: ghcr.io/community-valheim-tools/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - /media/ssd/valheim/worldname/config:/config
      - /media/ssd/valheim/worldnameh/data:/opt/valheim
      - /media/ssd/valheim/worldname/backups:/backups
    ports:
      - "2456-2458:2456-2458/udp"
    env_file:
      - /media/ssd/valheim/worldname/.env
    restart: always
    stop_grace_period: 2m